### ISSUE TITLE
Why rotate around Y axis and negate the y translation?

### ISSUE THREAD

**Issue by MooreManor** [saidwivedi/DSR#10]
I used NMR to render the image, but I found that the images were reversed. The images are shown below.

![image](https://user-images.githubusercontent.com/49632327/156174945-cc6d3478-160f-4862-8b10-85314cea6194.png)

And I found that in function `convert_camT_to_proj_mat`, you rotate around Y axis and negate the y translation.  After I commented on the lines to negate y rotation and y translation, the results seem correct.

https://github.com/saidwivedi/DSR/blob/7d55d173192a44ec567864befd2fb20e993098eb/dsr/semantic_rendering/data_utils.py#L151-L162 

Why do you do that extra operation? Did I make some mistakes or get something wrong? Thanks.

**Comment by saidwivedi** [comment]
In DSR, we use [SoftRas](https://github.com/ShichenLiu/SoftRas/tree/legacy) for rendering during the training. 

There is a typo in the comment which says it is for NMR but it is actually for SoftRas.

Following is a sample rendering during training using the `debug_rend_out()` function at [L170](https://github.com/saidwivedi/DSR/blob/7d55d173192a44ec567864befd2fb20e993098eb/dsr/losses/losses.py#L170)

![rend_0](https://user-images.githubusercontent.com/4973768/156189922-1bbfbb0b-55cf-419d-bcc7-9b71bb937d80.png)

**Comment by MooreManor** [comment]
Thanks!

**Comment by MooreManor** [comment]
@saidwivedi Is it due to the difference in the definition of coordinates between NMR and SoftRas?

**Comment by saidwivedi** [comment]
Yes it is.
