### ISSUE TITLE
Request for the propcessing code.

### ISSUE THREAD

**Issue by syguan96** [saidwivedi/DSR#11]
Hi @saidwivedi, excellent work! Would you mind releasing the code for processing the semantic masks?

**Comment by saidwivedi** [comment]
Thank you for your interest in the project. I used the [demo code](https://github.com/Gaoyiminggithub/Graphonomy#inference) of [Graphonomy](https://arxiv.org/abs/1904.04536) to generate semantic masks. As DSR expects a centre aligned single person as input, I used two additional steps for clean up-

- Using key-points to remove non-ROI
https://github.com/saidwivedi/DSR/blob/7d55d173192a44ec567864befd2fb20e993098eb/dsr/semantic_rendering/data_utils.py#L29-L39

- Removing small spurious masks
https://github.com/saidwivedi/DSR/blob/7d55d173192a44ec567864befd2fb20e993098eb/dsr/semantic_rendering/data_utils.py#L138

**Comment by syguan96** [comment]
Thank you for your kind reply! Help me a lot!
