### ISSUE TITLE
bbox mode

### ISSUE THREAD

**Issue by aespielberg** [saidwivedi/DSR#4]
Thank you for the cool project.  I'm able to run the openpose demo.  I want to try using a manually specified bbox.  Ignoring the fact that the bbox here isn't very tight, it fails execute on the demo image:

```
$ python demo.py --checkpoint dsr_data/dsr_w3DPW_checkpoint.pt --img examples/COCO_val_0544.jpg --bbox [0,0,640,427]
2021-10-16 21:01:17.524 | INFO     | dsr.models.hmr:load_pretrained:40 - Loading pretrained weights from dsr_data/dsr_w3DPW_checkpoint.pt
Traceback (most recent call last):
  File "demo.py", line 115, in <module>
    img = process_image(args.img, args.bbox, args.openpose, input_res=constants.IMG_RES)
  File "demo.py", line 84, in process_image
    center, scale = bbox_from_json(bbox_file)
  File "demo.py", line 60, in bbox_from_json
    with open(bbox_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '[0,0,640,427]'
```

Removing the [ ] brackets does not help.

**Comment by saidwivedi** [comment]
The `demo.py` file expects a json file for `bbox` as well. 

Just store the bounding box values in the format specified in SPIN repo https://github.com/nkolot/SPIN/blob/master/examples/im1010_bbox.json. It should work.

**Comment by aespielberg** [comment]
Thanks!
