### ISSUE TITLE
not good result for arms

### ISSUE THREAD

**Issue by zhaishengfu** [saidwivedi/DSR#5]
![image](https://user-images.githubusercontent.com/7630101/137829184-27d68f2c-857c-44ed-a749-ce5590351880.png)

thanks for sharing. I run the code to test my custom video, but find that the result is not so good. the arms will be wrong even for clear image. what the reason do you think it is ?

**Comment by saidwivedi** [comment]
Thank you for using our repo. Can you please share the command you used to run your demo along with the image and bounding box?

**Comment by zhaishengfu** [comment]
I read videos and do video inference.  the bbox is none and i use openpose keypoints 2d json

the code:
![image](https://user-images.githubusercontent.com/7630101/138013276-a804135c-1765-4a68-9fc4-22a45cbfb599.png)

the video:
https://user-images.githubusercontent.com/7630101/138013372-d347e3c3-558c-45c9-b4ad-a21f54b16060.mp4

the original image and resulting openpose json:
[testdouyin.zip](https://github.com/saidwivedi/DSR/files/7377565/testdouyin.zip)

**Comment by saidwivedi** [comment]
Thanks for sharing the data. Yes it doesn't output as expected. 

The probable reason being DSR doesn't perform quite well in case of occlusion (self-occlusion - as in the case above) and object occlusion as the Graphonomy segmentation doesn't work with occlusion (see [SupMat](https://openaccess.thecvf.com/content/ICCV2021/supplemental/Dwivedi_Learning_To_Regress_ICCV_2021_supplemental.pdf) for more discussion on this).

If your data has a lot of occlusions, you can try another method which tackles occlusions explicitly  - https://github.com/mkocabas/PARE

**Comment by zhaishengfu** [comment]
thanks for reply.

**Comment by saidwivedi** [comment]
I am closing this issue for now. Feel free to open it if you have more questions.
