### ISSUE TITLE
extracting the output

### ISSUE THREAD

**Issue by omarmohamed101** [saidwivedi/DSR#7]
i ran the demo and realized that the output is a png photo. 
How can i get the smpl parameters of the body?

**Comment by saidwivedi** [comment]
Sorry for the delayed response.

Yes, you can get SMPL parameters from the model.
`pred['pred_pose'] # SMPL Pose Parameters`
`pred['pred_shape'] # SMPL Shape Parameters`

The predicted output contains following information-
`dict_keys(['smpl_vertices', 'smpl_joints3d', 'smpl_joints2d', 'pred_cam_t', 'pred_pose', 'pred_cam', 'pred_shape'])
`

Feel free to open the issue if you have further questions
