### ISSUE TITLE
Require for DSR dataset

### ISSUE THREAD

**Issue by MooreManor** [saidwivedi/DSR#9]
Hello. Thanks for your great work!
I want to train DSR, but I found that the description of DSR was not quite clear as shown below.

```text
dataset_folders # Contains all datasets
├── coco
│   ├── grph_sequences # Contains psuedo-GT Graphonomy Segmentation
│   └── ...
└── h36m
│   ├── grph_sequences # Contains psuedo-GT Graphonomy Segmentation
│   └── ...
└── ... # Other datasets
```

I worry that the time spent preparing the data may be too long. Would you like to share the datasets on Google Drive or offer some scripts to process the raw datasets to the specified form of data? Thanks!

**Comment by saidwivedi** [comment]
Thank you for your interest in our work!

As we do not own the datasets, you will have to download from the respective sources after agreeing to their license agreement. However, I can clarify the steps for smooth processing.

The data preparation for DSR requires three main components:-

- **Images:** We use Human3.6, COCO and 3DPW datasets for training. Check the [SPIN data preparation](https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md#data-preparation) for more clarification. 

- **Human Pose Annotations:** For 3D annotations, we use the [SPIN data preprocessing](https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md#generate-dataset-files) script. For pseudo 3D annotations in case of COCO, we use the SMPL parameters given by [EFT](https://github.com/facebookresearch/eft#download-eft-fitting-data-json-formats)

- **Pseudo Human Clothing Segmentation:** After downloading the images for 3 datasets, we ran the [inference script](https://github.com/Gaoyiminggithub/Graphonomy#inference) of Graphonomy and used the results as pseudo human clothing segmentation. For more details kindly refer to the [Sup. Mat. ](https://openaccess.thecvf.com/content/ICCV2021/supplemental/Dwivedi_Learning_To_Regress_ICCV_2021_supplemental.pdf)

**Comment by MooreManor** [comment]
Thanks for your detailed answer!
